name: commit-checks
on: [push]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  commit-checks:
    runs-on: windows-2022
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [commit-checks]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build
      - run: npx nx affected --target=test --parallel
      - run: npx nx affected --target=lint
      - run: npx nx-cloud stop-all-agents

  agents:
    runs-on: ubuntu-latest
    name: build test lint
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: npm ci
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  build-tauri:
    strategy:
      fail-fast: false

      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Uninstall tauri locally
        run: cd apps/tauri-client && npm un @tauri-apps/cli
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: npm install
        run: npm install
      - name: build tauri-client
        run: npx nx build tauri-client
